=== pbujko/tablica/be/tablicaBe/src/test/resources/atts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="allAtts">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="attribute"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="2" maxOccurs="unbounded" ref="choice"/>
            </xs:sequence>
            <xs:attribute name="label" use="required" type="xs:string"/>
            <xs:attribute name="catId" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="choice">
        <xs:complexType>
            <xs:attribute name="label" use="required" type="xs:string"/>
            <xs:attribute name="id" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== pbujko/tablica/ui/tablica/grails-app/conf/attributes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<allAtts xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='atts.xsd'>
    <attribute catId="1.1" id="cat1_1" label="Marka">
        <choice label="choice 1" id="1_1"/>
        <choice label="choice 2" id="1_2"/>
        <choice label="choice 3" id="1_3"/>
        <choice label="choice 4" id="1_4"/>
        <choice label="choice 5" id="1_5"/>
    </attribute>
      
    <attribute catId="1.1" id="cat2_1" label="Paliwo">
        <choice label="choice 1" id="2_1"/>
        <choice label="choice 2" id="2_2"/>
        <choice label="choice 3" id="2_3"/>
    </attribute>
    
    <attribute catId="1.2" id="cat2_2" label="att2 cat2">
        <choice label="choice 1" id="2_1"/>
        <choice label="choice 2" id="2_2"/>
        <choice label="choice 3" id="2_3"/>
    </attribute>    
</allAtts>

=== pbujko/tablica/be/tablicaBe/src/test/resources/attributes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<allAtts xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='atts.xsd'>
    <attribute catId="1" id="cat1_1" label="att1 cat1" code="att1_cat1">
        <choice label="choice 1" id="cat1_1_1" code="choice_111"/>
        <choice label="choice 2" id="1_1_2" />
        <choice label="choice 3" id="1_1_3" code="choice_113"/>
        <choice label="choice 4" id="1_1_4" code="choice_114"/>
        <choice label="choice 5" id="1_1_5" code="choice_115"/>
    </attribute>
      
    <attribute catId="2" id="cat2_1" label="att1 cat2" code="att1_cat2">
        <choice label="choice 1" id="2_1_1" code="choice_211"/>
        <choice label="choice 2" id="2_1_2" code="choice_212"/>
        <choice label="choice 3" id="2_1_3" code="choice_213"/>
    </attribute>
    
    <attribute catId="2" id="cat2_2" label="att2 cat2" code="att2_cat2">
        <choice label="choice 1" id="2_2_1" code="choice_221"/>
        <choice label="choice 2" id="2_2_2" code="choice_223"/>
        <choice label="choice 3" id="2_2_3" code="choice_223"/>
    </attribute>    
</allAtts>
