=== pbujko/tablica/be/tablicaBe/src/test/resources/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="allNodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="node"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="node">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="node"/>
            </xs:sequence>
            <xs:attribute name="label" use="required" type="xs:string"/>
            <xs:attribute name="id" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== pbujko/tablica/ui/tablica/grails-app/conf/nodesData.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<allNodes xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='test.xsd'>
    <node label="kategoria top 0.1" id="0.1" code="node-01">      
        <node label="kat 0.1,1" id="1" code="to-jest-node-1">
        <!-- ad -->
            <node label="NODE 0.1,1,1" id="11" code="node-sroed-11"/>
            <!-- ad -->
            <node label="NODE 0.1,1,2" id="12" code="node-12">
                <node label="NODE_0.1,1,2,1" id="121" code="a-to-jest-node-121"/>
                <!-- ad -->
            </node>
        </node>
        <node label="kat 0.1,2" id="0.1,2" code="to-jest-node-01-2"/>
    </node>
    <node label="kategoria top 0.2" id="0.2" code="node-0.2">      
        <node label="0.2,1" id="2" code="node-2-trala-la"/>
    </node>

    <node label="kategoria top 0.3" id="0.3" code="to-jest-dlugi-code-node-0.3">
        <node label="0.3,1" id="3" code="node-3"/>
    </node>
</allNodes>
